general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "0px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "80px"
    right: "50px"
    bottom: "50px"
    left: "50px"
    # top: "50px"
    # right: "20px"
    # bottom: "20px"
    # left: "20px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "100%"

  # Visual effects to apply to non-focused windows.
  # Exclusive to win 11
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  # 'tiling', 'floating'.
  initial_state: "tiling"

  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "0"
    display_name: "0 edge"
    bind_to_monitor: 0
    keep_alive: true
  - name: "1"
    display_name: "1 browser"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    display_name: "2 terminal"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    display_name: "3 editor"
    bind_to_monitor: 1
    keep_alive: false
  - name: "4"
    display_name: "4 explorer"
    bind_to_monitor: 1
    keep_alive: false
  - name: "5"
    display_name: "5 games"
    bind_to_monitor: 1
    keep_alive: false
  - name: "6"
    display_name: "6 others"
    bind_to_monitor: 1
    keep_alive: false
  - name: "7"
    display_name: "7 obsidian"
    bind_to_monitor: 1
    keep_alive: false
  - name: "8"
    display_name: "8 misc"
    bind_to_monitor: 1
    keep_alive: false
  - name: "9"
    display_name: "9 launchers"
    bind_to_monitor: 1
    keep_alive: false
  - name: "10"
    display_name: "10 stuff"
    bind_to_monitor: 1
    keep_alive: false

window_rules:
  # ---------------------------------------------------------------------------
  # IGNORE
  # ---------------------------------------------------------------------------
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }

      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }

      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

      - window_process: { equals: "SnippingTool" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 1
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 1", focus --workspace 1]
    match:
      - window_process: { equals: "zen" }
      - window_process: { equals: "firefox" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 0
  # ---------------------------------------------------------------------------
  # Move Edge (for dev) and pip windows to second screen
  # The size commands make it so edge and the pip fill the screen properly
  - commands: ["move --workspace 0", "size --width 1400 --height 1675"]
    match:
      - window_process: { equals: "msedge" }

  - commands: ["move --workspace 0", "size --width 1400 --height 754"]
    match:
      - window_title: { equals: "Picture-in-Picture" }
        window_class: { equals: "MozillaDialogClass" }
        window_process: { equals: "zen" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 2
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 2"]
    match:
      - window_process: { equals: "WindowsTerminal" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 3
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 3", "focus --workspace 3"]
    match:
      - window_process: { equals: "Code" }
      - window_process: { equals: "neovide" }
      - window_process: { equals: "devenv" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 4
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 4", "focus --workspace 4"]
    match:
      - window_process: { equals: "explorer" }
        window_class: { not_equals: "OperationStatusWindow" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 5
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 5", "focus --workspace 5"]
    match:
      - window_process: { equals: "Fusion360" }
      - window_process: { equals: "retroarch" }
      - window_process: { equals: "javaw" }
        window_title: { regex: "Minecraft" }

  - commands: ["move --workspace 5", "set-floating"]
    match:
      - window_process: { equals: "Minecraft" }
        window_title: { equals: "Minecraft Launcher" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 6
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 6"]
    match:

  # ---------------------------------------------------------------------------
  # WORKSPACE 7
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 7"]
    match:
      - window_process: { equals: "anki" }
      - window_process: { equals: "Obsidian" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 8
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 8", "focus --workspace 8"]
    match:
      - window_process: { equals: "Plex" }
      - window_process: { equals: "SumatraPDF" }
      - window_process: { equals: "vlc" }
      - window_process: { equals: "calibre" }
      - window_process: { equals: "calibre-parallel" }
      - window_process: { equals: "VirtualBoxVM" }

  - commands: ["move --workspace 8", "set-fullscreen"]
    match:
      - window_process: { equals: "Unity" }

  - commands: ["move --workspace 8", "set-floating", "set-minimized"]
    match:
      - window_process: { equals: "Unity" }
        window_class: { equals: "ConsoleWindowClass" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 9
  # ---------------------------------------------------------------------------
  # Move Steam main window to workspace 9
  - commands: ["move --workspace 9"]
    match:
      - window_process: { equals: "Unity Hub" }
      - window_process: { equals: "steamwebhelper" }
        window_title: { equals: "Steam" }

  # Move Steam friends list to workspace 9 and resize it
  - commands: ["move --workspace 9", "size --width 440"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { equals: "Freundesliste" }

  # Set all other Steam windows to floating
  - commands: ["move --workspace 9", "set-floating"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { not_regex: "Steam|Freundesliste" }

  - commands: ["move --workspace 9"]
    match:
      - window_process: { equals: "EpicGamesLauncher" }
      - window_process: { equals: "GalaxyClient" }

  # ---------------------------------------------------------------------------
  # WORKSPACE 10
  # ---------------------------------------------------------------------------
  - commands: ["move --workspace 10"]
    match:
      - window_process: { equals: "Discord" }

  # ---------------------------------------------------------------------------
  # FLOATING
  # ---------------------------------------------------------------------------
  - commands: ["set-floating"]
    match:
      # Set Browser extension windows to floating.
      - window_process: { equals: "zen" }
        window_title: { regex: "Extension" }
        window_class: { equals: "MozillaDialogClass" }
      - window_process: { equals: "Taskmgr" }
      - window_title: { regex: "calc|Rechner" }
      - window_title: { regex: "Window Spy" }
      - window_process: { equals: "VirtualBoxVM" }
        window_title: { equals: "Close Virtual Machine" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  # - commands: ['focus --direction left']
  #   bindings: ['alt+h', 'alt+left']
  # - commands: ['focus --direction right']
  #   bindings: ['alt+l', 'alt+right']
  # - commands: ['focus --direction up']
  #   bindings: ['alt+k', 'alt+up']
  # - commands: ['focus --direction down']
  #   bindings: ['alt+j', 'alt+down']
  - commands: ["focus --direction left"]
    bindings: ["alt+left", "ctrl+alt+h"]
  - commands: ["focus --direction right"]
    bindings: ["alt+right", "ctrl+alt+l"]
  - commands: ["focus --direction up"]
    bindings: ["alt+up", "ctrl+alt+k"]
  - commands: ["focus --direction down"]
    bindings: ["alt+down", "ctrl+alt+j"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    # bindings: ['alt+p']
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  # - commands: ['resize --height -2%']
  #   bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+shift+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["alt+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  - commands: ["toggle-floating --centered"]
    bindings: ["alt+c"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ['shell-exec cmd']
  #   bindings: ['alt+enter']

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ["focus --next-active-workspace"]
    bindings: ["alt+s", "alt+n"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["alt+a", "alt+p"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 0"]
    bindings: ["alt+0", "alt+h"]
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1", "alt+f"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2", "alt+j"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3", "alt+k"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4", "alt+l"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5", "alt+;"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  # - commands: ["move-workspace --direction left"]
  #   bindings: ["alt+shift+a"]
  # - commands: ["move-workspace --direction right"]
  #   bindings: ["alt+shift+f"]
  # - commands: ["move-workspace --direction up"]
  #   bindings: ["alt+shift+d"]
  # - commands: ["move-workspace --direction down"]
  #   bindings: ["alt+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
